id: A68CF32A5
title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of Glory'
type: translation
pechas:
- I442C4844
- I05E50500
- I0020749C
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:04:54.080791
  last_modified_at: 2023-01-04 13:04:54.080795
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I442C4844/CAF0: 31B2
  I05E50500/0743: 31B2
  I0020749C/B065: 31B2
